<div class="row">
	@include('admin._partials.index_info_block', ['title' => $usersCount,
		'label' => 'Пользователи',
		'url' => 'users',
		'style' => 'primary',
		'icon' => 'fa-users'])
	@include('admin._partials.index_info_block', ['title' => $domensCount,
		'label' => 'Домены',
		'url' => 'users_site',
		'style' => 'primary',
		'icon' => 'fa-tags'])
	@include('admin._partials.index_info_block', ['title' => $segmentCount,
		'label' => 'Сегменты',
		'url' => 'segments',
		'style' => 'primary',
		'icon' => 'fa-bars'])
	@include('admin._partials.index_info_block', ['title' => $subscribersCount,
		'label' => 'Подписчики',
		'url' => 'subscribers',
		'style' => 'primary',
		'icon' => 'fa-users'])
</div>
